[2025-08-12T18:26:45.292+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-12T18:26:46.038+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: user_automation.stream_data_from_api manual__2025-08-12T18:26:39.545966+00:00 [queued]>
[2025-08-12T18:26:46.101+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: user_automation.stream_data_from_api manual__2025-08-12T18:26:39.545966+00:00 [queued]>
[2025-08-12T18:26:46.108+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2025-08-12T18:26:46.258+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): stream_data_from_api> on 2025-08-12 18:26:39.545966+00:00
[2025-08-12T18:26:46.348+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'user_automation', 'stream_data_from_api', 'manual__2025-08-12T18:26:39.545966+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/kafka_stream.py', '--cfg-path', '/tmp/tmpam9l82aa']
[2025-08-12T18:26:46.370+0000] {standard_task_runner.py:91} INFO - Job 2: Subtask stream_data_from_api
[2025-08-12T18:26:46.369+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=312) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-08-12T18:26:46.374+0000] {standard_task_runner.py:63} INFO - Started process 313 to run task
[2025-08-12T18:26:46.805+0000] {task_command.py:426} INFO - Running <TaskInstance: user_automation.stream_data_from_api manual__2025-08-12T18:26:39.545966+00:00 [running]> on host f2066d2b2ad6
[2025-08-12T18:26:47.774+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airscholar' AIRFLOW_CTX_DAG_ID='user_automation' AIRFLOW_CTX_TASK_ID='stream_data_from_api' AIRFLOW_CTX_EXECUTION_DATE='2025-08-12T18:26:39.545966+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-12T18:26:39.545966+00:00'
[2025-08-12T18:26:47.779+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-12T18:26:52.548+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <connecting> [IPv4 ('172.18.0.3', 29092)]>: connecting to broker:29092 [('172.18.0.3', 29092) IPv4]
[2025-08-12T18:26:52.579+0000] {conn.py:618} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <checking_api_versions_recv> [IPv4 ('172.18.0.3', 29092)]>: Broker version identified as 2.6
[2025-08-12T18:26:52.579+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <connected> [IPv4 ('172.18.0.3', 29092)]>: Connection complete.
[2025-08-12T18:26:54.745+0000] {conn.py:396} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=broker:29092 <connecting> [IPv4 ('172.18.0.3', 29092)]>: connecting to broker:29092 [('172.18.0.3', 29092) IPv4]
[2025-08-12T18:26:54.749+0000] {conn.py:457} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=broker:29092 <connected> [IPv4 ('172.18.0.3', 29092)]>: Connection complete.
[2025-08-12T18:26:54.751+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=bootstrap-0 host=broker:29092 <connected> [IPv4 ('172.18.0.3', 29092)]>: Closing connection. 
[2025-08-12T18:26:54.775+0000] {cluster.py:316} ERROR - Topic users_created not found in cluster metadata
[2025-08-12T18:27:53.095+0000] {conn.py:945} INFO - <BrokerConnection client_id=kafka-python-producer-1, node_id=1 host=broker:29092 <connected> [IPv4 ('172.18.0.3', 29092)]>: Closing connection. 
[2025-08-12T18:27:53.102+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-08-12T18:27:53.109+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-12T18:27:53.156+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=user_automation, task_id=stream_data_from_api, execution_date=20250812T182639, start_date=20250812T182646, end_date=20250812T182753
[2025-08-12T18:27:53.245+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-08-12T18:27:53.329+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-12T18:27:53.337+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
